production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: p42r0327_pZym
  pool: 5
  username: p42r0327_pZym
  password: 8ym9crw3
  socket: /tmp/mysql.sock

development_test:
  adapter: mysql2
  encoding: utf8
  database: p42r0327_test
  username: p42r0327_test
  password: test

development:
  development_test
